# Generated by Django 4.0.3 on 2022-05-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('localidad', models.CharField(max_length=30)),
                ('sobrevos', models.TextField(max_length=2000, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RutaBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRuta', models.CharField(max_length=30)),
                ('tipoRuta', models.CharField(max_length=30)),
                ('distancia', models.FloatField()),
                ('dificultad', models.CharField(max_length=10)),
                ('tiempo', models.IntegerField()),
                ('comentario', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
