# Generated by Django 4.0.3 on 2022-05-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCleta', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='sobrevos',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rutabici',
            name='tiempo',
            field=models.TimeField(),
        ),
    ]
